apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-game-app
  labels:
    app: js-game-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: js-game-app
  template:
    metadata:
      labels:
        app: js-game-app
    spec:
      containers:
        - name: js-game-app
          image: internaldev/jsgame:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: js-game-app-service
  name: js-game-app-service
spec:
  ports:
    - name: "3000-80"
      port: 3000
      protocol: TCP
      targetPort: 80
  selector:
    app: js-game-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: js-game-app-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: js-game-app-service
                port:
                  number: 3000
